function topbar(){return `<header class="topbar"><div class="brandline"><div class="brand">CAPITAL ASCENT <span class="tiny">BROWSER EDITION</span></div><div class="week">Y${state.year} / W${state.week}</div></div><div class="metrics">
  <div class="metric"><small>会社現金</small><b>${yen(state.company.cash)}</b></div><div class="metric"><small>会社価値</small><b>${yen(companyValue(state))}</b></div><div class="metric"><small>個人現金</small><b>${yen(state.personal.cash)}</b></div><div class="metric"><small>個人純資産</small><b>${yen(personalNetWorth(state))}</b></div>
  <div class="metric"><small>直近週利益</small><b class="${state.company.lastWeekProfit>=0?'positive':'negative'}">${yen(state.company.lastWeekProfit)}</b></div><div class="metric"><small>政策金利</small><b>${pct(state.macro.rate)}</b></div></div></header>`;}
function nav(){const items=[['overview','⌂','HQ'],['operations','▦','事業'],['market','↗','市場'],['microcap','◆','Microcap'],['pe','▤','PE'],['legacy','★','Legacy']];return `<nav class="nav">${items.map(([id,ic,l])=>`<button data-tab="${id}" class="${tab===id?'active':''}"><span class="ico">${ic}</span>${l}</button>`).join('')}</nav>`;}
function overview(){const v=companyValue(state), ex=state.career.exitRecords.length;return `<main><div class="hero"><h1>${state.player.name}</h1><div class="strap">1社を育て、資本市場へ出し、Exit後はPEファームへ。公開市場のMicrocap投資も同じ週次時間軸で進む。</div><div class="actions"><button class="btn primary" data-act="advance">1週進める</button><button class="btn" data-act="advance13">13週進める</button></div></div>
<div class="grid" style="margin-top:10px"><section class="card half"><h2>Operating Snapshot</h2><div class="kpis"><div class="kpi"><div class="label">売上 / 週</div><div class="value">${yen(state.company.lastWeekRevenue)}</div></div><div class="kpi"><div class="label">利益 / 週</div><div class="value ${state.company.lastWeekProfit>=0?'positive':'negative'}">${yen(state.company.lastWeekProfit)}</div></div><div class="kpi"><div class="label">会社負債</div><div class="value">${yen(state.company.debt)}</div></div><div class="kpi"><div class="label">Exit回数</div><div class="value">${ex}</div></div></div>
<div class="actions"><button class="btn good" data-act="ipo" ${state.company.public?'disabled':''}>IPO</button><button class="btn danger" data-act="sellCompany">会社売却</button></div><p class="sub">IPO条件: 企業価値8,000万円以上＋直近黒字。会社売却: 企業価値1.2億円以上＋80週以上。</p></section>
<section class="card half"><h2>Macro Tape</h2><div class="kpis"><div class="kpi"><div class="label">景気サイクル</div><div class="value">${state.macro.cycle.toFixed(2)}</div></div><div class="kpi"><div class="label">インフレ</div><div class="value">${pct(state.macro.inflation)}</div></div><div class="kpi"><div class="label">不動産Cycle</div><div class="value">${state.macro.realEstate.toFixed(2)}</div></div><div class="kpi"><div class="label">PE解禁</div><div class="value">${state.pe.unlocked?'OPEN':'LOCKED'}</div></div></div></section>
<section class="card"><h2>Event Feed</h2><div class="news">${state.news.slice(0,10).map(n=>`<div class="news-item ${n.type||''}"><span class="tiny">W${n.week}</span> ${n.msg}</div>`).join('')||'<div class="sub">まだイベントはありません。</div>'}</div></section></div></main>`;}
function operations(){const businessCards=Object.values(PILLARS).map(p=>{const b=state.company.businesses[p.id];if(!b)return `<section class="card third"><h2>${p.icon} ${p.name}</h2><p class="sub">${p.desc}</p><button class="btn primary wide" data-add-business="${p.id}">参入する</button></section>`;const stores=state.company.stores.filter(x=>x.businessID===p.id);return `<section class="card half"><div class="brandline"><h2>${p.icon} ${p.name}</h2><span class="pill live">ACTIVE</span></div><p class="sub">${p.desc}</p>
<div class="kpis"><div class="kpi"><div class="label">Quality</div><div class="value">${b.quality.toFixed(0)}</div></div><div class="kpi"><div class="label">Brand</div><div class="value">${b.brand.toFixed(0)}</div></div><div class="kpi"><div class="label">Efficiency</div><div class="value">${b.efficiency.toFixed(0)}</div></div><div class="kpi"><div class="label">DX</div><div class="value">${b.digital.toFixed(0)}</div></div></div>
<div class="control"><div><div class="name">基準価格</div><div class="desc">需要と粗利の基本レバー</div></div><input data-business-field="price" data-business="${p.id}" value="${Math.round(b.price)}" inputmode="numeric"></div>
<div class="control"><div><div class="name">広告 / 週</div><div class="desc">ブランドと需要を押し上げる</div></div><input data-business-field="adSpend" data-business="${p.id}" value="${Math.round(b.adSpend)}" inputmode="numeric"></div>
${p.id==='conveni'?`<div class="control"><div><div class="name">PB比率</div><div class="desc">0〜45%。粗利改善と廃棄リスク</div></div><select data-business-field="pbRatio" data-business="${p.id}"><option value="0" ${b.pbRatio===0?'selected':''}>0%</option><option value="0.15" ${b.pbRatio===.15?'selected':''}>15%</option><option value="0.3" ${b.pbRatio===.3?'selected':''}>30%</option><option value="0.45" ${b.pbRatio===.45?'selected':''}>45%</option></select></div>`:''}
${p.id==='gym'?`<div class="control"><div><div class="name">会員戦略</div></div><select data-business-field="gymStrategy" data-business="${p.id}"><option value="standard" ${b.gymStrategy==='standard'?'selected':''}>Standard</option><option value="offPeak" ${b.gymStrategy==='offPeak'?'selected':''}>Off-Peak</option><option value="premium" ${b.gymStrategy==='premium'?'selected':''}>Premium</option></select></div>`:''}
<div class="actions"><button class="btn" data-invest="quality" data-business="${p.id}">品質投資 50万</button><button class="btn" data-invest="brand" data-business="${p.id}">ブランド 50万</button><button class="btn" data-invest="efficiency" data-business="${p.id}">効率 50万</button><button class="btn" data-invest="digital" data-business="${p.id}">DX 50万</button>${p.id!=='productVentures'?`<button class="btn primary" data-open-store="${p.id}">新規出店</button>`:''}</div>
${stores.length?`<div class="scroll" style="margin-top:10px"><table class="table"><tr><th>拠点</th><th>売上</th><th>利益</th><th>Units</th></tr>${stores.map(s=>`<tr><td>${s.name}</td><td>${yen(s.lastRevenue)}</td><td class="${s.lastProfit>=0?'positive':'negative'}">${yen(s.lastProfit)}</td><td>${s.lastUnits.toLocaleString()}</td></tr>`).join('')}</table></div>`:''}</section>`;}).join('');return `<main><div class="grid">${businessCards}</div></main>`;}
function market(){return `<main><div class="grid"><section class="card half"><h2>Capital Markets</h2><div class="kpis"><div class="kpi"><div class="label">公開会社</div><div class="value">${state.company.public?'YES':'NO'}</div></div><div class="kpi"><div class="label">Founder持分</div><div class="value">${pct(state.company.founderOwnership)}</div></div><div class="kpi"><div class="label">企業価値</div><div class="value">${yen(companyValue(state))}</div></div><div class="kpi"><div class="label">Exit履歴</div><div class="value">${state.career.exitRecords.length}</div></div></div><div class="actions"><button class="btn good" data-act="ipo" ${state.company.public?'disabled':''}>IPOを実行</button><button class="btn danger" data-act="sellCompany">会社を売却</button></div></section>
<section class="card half"><h2>Corporate Finance & M&A</h2><div class="kpis"><div class="kpi"><div class="label">会社負債</div><div class="value">${yen(state.company.debt)}</div></div><div class="kpi"><div class="label">信用</div><div class="value">${state.company.credit.toFixed(0)}</div></div><div class="kpi"><div class="label">子会社</div><div class="value">${state.company.subsidiaries}</div></div><div class="kpi"><div class="label">Founder持分</div><div class="value">${pct(state.company.founderOwnership)}</div></div></div><div class="actions"><button class="btn" data-act="borrow">銀行借入</button><button class="btn" data-act="repay">返済</button><button class="btn primary" data-act="acquireSub">子会社をM&A</button><button class="btn danger" data-act="sellSub" ${state.company.subsidiaries<=0?'disabled':''}>子会社売却</button></div></section><section class="card"><h2>Exit Record</h2>${state.career.exitRecords.length?`<div class="scroll"><table class="table"><tr><th>種類</th><th>週</th><th>実現額</th><th>企業価値</th></tr>${state.career.exitRecords.slice().reverse().map(x=>`<tr><td>${x.type}</td><td>${x.week}</td><td>${yen(x.realized)}</td><td>${yen(x.value)}</td></tr>`).join('')}</table></div>`:'<p class="sub">Exitを1回経験するとPEモードが永久解禁されます。</p>'}</section></div></main>`;}
